
ultimate_cron.settings:
  type: config_entity
  label: 'Ultimate cron settings'
  mapping:
    bypass_transactional_safe_connection:
      type: boolean
      label: Bypass transactional connection
    threshold_autorun:
      type: integer
      label: Interval for runs
    launcher:
      type: string
      lable: Launcher for Cron
    early_page_flush:
      type: boolean
      label: Toggle execution order
    user_agent:
      type: string
      label: User Agent triggering the launcher
    queue_enabled:
      type: boolean
      label: Toggle queing jobs
    lease_time:
      type: integer
      label: Time to claim item
    time:
      type: integer
      label: Time to process item
    empty_delay:
      type: integer
      lebel: Time to idle when queue is empty
    item_delay:
      type: integer
      label: Time to idle when finished with item
    throttle:
      type: boolean
      label: Toggles throttling of queues
    threads:
      type: integer
      label: Number of threads for queues
    threshold:
      type: integer
      label: Number of items needed for a queue
    poorman_keepalive:
      type: boolean
      label: Trigger Poormans
    thread:
      type: string
      label: Which thread to use
    max_threads:
      type: integer
      label: Maximum number of threads
    lock_timeout:
      type: integer
      label: Time to lock job
    max_execution_time:
      type: integer
      label: Maximum time for the job to run
    bin:
      type: string
      label: The cache bin to use
    timeout:
      type: integer
      label: Time until cache expires
    method:
      type: integer
      label: The method used for log retention
    expire:
      type: integer
      label: Time until expiration
    retain:
      type: integer
      label: Maximum number of logs to keep
    catch_up:
      type: integer
      label: Stop between job runs
    rules:
      type: sequence
      label: Array with rules
      sequence:
        type: string
        label: Formatted rule
    rule:
      type: string
      label: Rule for Simple scheduler

# @todo make schema pluggable
ultimate_cron.job.*:
  type: config_entity
  label: 'Cron Job'
  mapping:
    title:
      type: label
      label: 'Title'
    id:
      type: string
      label: 'Machine-readable name'
    module:
      type: string
      label: 'Module Name'
    callback:
      type: string
      label: 'Callback'
    scheduler:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Scheduler'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
          mapping:
            rules:
              type: sequence
              label: Scheduler rules
              sequence:
                - type: string
                  label: Scheduling rule
            catch_up:
              type: integer
              label: 'Timeout (s) after job run'
    launcher:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Launcher'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
          mapping:
            timeouts:
              type: mapping
              label: Timeout settings
              mapping:
                lock_timeout:
                  type: integer
                  label: Lock timeout
                max_execution_time:
                  type: integer
                  label: Max execution time
            launcher:
              type: mapping
              label: Launcher settings
              mapping:
                max_threads:
                  type: integer
                  label: Max threads
                poorman_keepalive:
                  type: boolean
                  label: Keepalive
    logger:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Logger'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
          mapping:
            method:
              type: string
              label: Method
            expire:
              type: integer
              label: Expiration
            retain:
              type: integer
              label: Retain X amount of logs
